config/routes.rb
Shepherd::Application.routes.draw do
  get "scheduler/index"

  resources :user_schedules

  resources :users

  match "/auth/:provider/callback" => "sessions#callback"
  match "/auth/failure" => "sessions#failure"
  match "/logout" => "sessions#destroy", :as => :logout

  root :to => 'scheduler#index'

  match ':controller(/:action(/:id(.:format)))'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_schedules

  def self.create_with_omniauth auth
    create! do |user|
      user[:provider] = auth["provider"]
      user[:uid] = auth["uid"]
      user[:name] = auth["info"]["name"]
      user[:screen_name] = auth["info"]["nickname"]
      user[:image] = auth["info"]["image"]
    end
  end

end

app/models/user_schedule.rb
class UserSchedule < ActiveRecord::Base
	belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :reset_session_expires

  private

  def reset_session_expires
    request.session_options[:expire_after] = 2.weeks
  end

  def current_user
    @current_user ||= User.where( id: session[:user_id] ).first
  end

  helper_method :current_user

end

app/controllers/scheduler_controller.rb
class SchedulerController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def callback
    auth = request.env["omniauth.auth"]
    user = User.where( provider: auth["provider"], uid: auth["uid"] ).first || User.create_with_omniauth( auth )
    session[:user_id] = user.id
    redirect_to :root, notice: "login"
  end

  def destroy
    session[:user_id] = nil
    redirect_to :root, notice: "Logged out"
  end

  def failure
    render text: "<span style='color: red;'>Auth Failure</span>"
  end
end

app/controllers/user_schedules_controller.rb
class UserSchedulesController < ApplicationController
  # GET /user_schedules
  # GET /user_schedules.json
  def index
    @user_schedules = UserSchedule.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_schedules }
    end
  end

  # GET /user_schedules/1
  # GET /user_schedules/1.json
  def show
    @user_schedule = UserSchedule.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_schedule }
    end
  end

  # GET /user_schedules/new
  # GET /user_schedules/new.json
  def new
    @user_schedule = UserSchedule.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_schedule }
    end
  end

  # GET /user_schedules/1/edit
  def edit
    @user_schedule = UserSchedule.find(params[:id])
  end

  # POST /user_schedules
  # POST /user_schedules.json
  def create
    @user_schedule = UserSchedule.new(params[:user_schedule])

    respond_to do |format|
      if @user_schedule.save
        format.html { redirect_to @user_schedule, notice: 'User schedule was successfully created.' }
        format.json { render json: @user_schedule, status: :created, location: @user_schedule }
      else
        format.html { render action: "new" }
        format.json { render json: @user_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_schedules/1
  # PUT /user_schedules/1.json
  def update
    @user_schedule = UserSchedule.find(params[:id])

    respond_to do |format|
      if @user_schedule.update_attributes(params[:user_schedule])
        format.html { redirect_to @user_schedule, notice: 'User schedule was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_schedules/1
  # DELETE /user_schedules/1.json
  def destroy
    @user_schedule = UserSchedule.find(params[:id])
    @user_schedule.destroy

    respond_to do |format|
      format.html { redirect_to user_schedules_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scheduler_helper.rb
module SchedulerHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_schedules_helper.rb
module UserSchedulesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shepherd</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if current_user %>
<%= current_user.name %> : <%= link_to "Logout" , logout_path %>
<% else %>
<%= link_to "Facebook Login", "/auth/facebook" %>
<br/>
<%= link_to "Twitter Login", "/auth/twitter" %>
<% end %>

<%= yield %>

</body>
</html>

app/views/user_schedules/_form.html.erb
<%= form_for(@user_schedule) do |f| %>
  <% if @user_schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_schedule.errors.count, "error") %> prohibited this user_schedule from being saved:</h2>

      <ul>
      <% @user_schedule.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_schedules/edit.html.erb
<h1>Editing user_schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_schedule %> |
<%= link_to 'Back', user_schedules_path %>

app/views/user_schedules/index.html.erb
<h1>Listing user_schedules</h1>

<table>
  <tr>
    <th>Date</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_schedules.each do |user_schedule| %>
  <tr>
    <td><%= user_schedule.date %></td>
    <td><%= user_schedule.status %></td>
    <td><%= link_to 'Show', user_schedule %></td>
    <td><%= link_to 'Edit', edit_user_schedule_path(user_schedule) %></td>
    <td><%= link_to 'Destroy', user_schedule, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User schedule', new_user_schedule_path %>

app/views/user_schedules/new.html.erb
<h1>New user_schedule</h1>

<%= render 'form' %>

<%= link_to 'Back', user_schedules_path %>

app/views/user_schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @user_schedule.date %>
</p>

<p>
  <b>Status:</b>
  <%= @user_schedule.status %>
</p>


<%= link_to 'Edit', edit_user_schedule_path(@user_schedule) %> |
<%= link_to 'Back', user_schedules_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>